import type { Order } from '../types/orders.types';

export const ORDERS: Order[] = [
  {
    id: '1',
    orderNumber: 'ORD-1001',
    date: '2026-07-20',
    status: 'Delivered',
    total: 1347,
    subtotal: 1298,
    shipping: 49,
    items: [
      {
        id: '1',
        productId: '1',
        name: 'Classic Navy Shirt',
        price: 899,
        quantity: 1,
        image: '/images/products/shirt.jpg',
      },
      {
        id: '2',
        productId: '2',
        name: 'Slim Fit Chinos',
        price: 449,
        quantity: 1,
        image: '/images/products/chinos.jpg',
      },
    ],
    address: {
      name: 'Test User',
      mobile: '9876543210',
      line1: '123 Main Street',
      line2: 'Apartment 4B',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400001',
    },
    deliveryMethod: 'Standard Delivery',
    paymentMethod: 'Cash on Delivery',
    trackingEvents: [
      {
        id: 't1',
        title: 'Order Placed',
        description: 'Your order has been confirmed.',
        timestamp: '2026-07-20T10:00:00Z',
        status: 'completed',
      },
      {
        id: 't2',
        title: 'Packed',
        description: 'Your order has been packed.',
        timestamp: '2026-07-20T14:00:00Z',
        status: 'completed',
      },
      {
        id: 't3',
        title: 'Shipped',
        description: 'Your order is on the way.',
        timestamp: '2026-07-21T09:00:00Z',
        status: 'completed',
      },
      {
        id: 't4',
        title: 'Delivered',
        description: 'Your order has been delivered.',
        timestamp: '2026-07-23T11:00:00Z',
        status: 'completed',
      },
    ],
  },
  {
    id: '2',
    orderNumber: 'ORD-1002',
    date: '2026-07-23',
    status: 'Shipped',
    total: 899,
    subtotal: 899,
    shipping: 0,
    items: [
      {
        id: '3',
        productId: '3',
        name: 'Casual Polo T-Shirt',
        price: 899,
        quantity: 1,
        image: '/images/products/polo.jpg',
      },
    ],
    address: {
      name: 'Test User',
      mobile: '9876543210',
      line1: '123 Main Street',
      line2: 'Apartment 4B',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400001',
    },
    deliveryMethod: 'Express Delivery',
    paymentMethod: 'Pay Online',
    trackingEvents: [
      {
        id: 't1',
        title: 'Order Placed',
        description: 'Your order has been confirmed.',
        timestamp: '2026-07-23T08:00:00Z',
        status: 'completed',
      },
      {
        id: 't2',
        title: 'Packed',
        description: 'Your order has been packed.',
        timestamp: '2026-07-23T12:00:00Z',
        status: 'completed',
      },
      {
        id: 't3',
        title: 'Shipped',
        description: 'Your order is on the way.',
        timestamp: '2026-07-24T09:00:00Z',
        status: 'active',
      },
    ],
  },
  {
    id: '3',
    orderNumber: 'ORD-1003',
    date: '2026-07-24',
    status: 'Processing',
    total: 2199,
    subtotal: 2150,
    shipping: 49,
    items: [
      {
        id: '4',
        productId: '4',
        name: 'Premium Linen Shirt',
        price: 1099,
        quantity: 2,
        image: '/images/products/linen.jpg',
      },
    ],
    address: {
      name: 'Test User',
      mobile: '9876543210',
      line1: '123 Main Street',
      line2: 'Apartment 4B',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400001',
    },
    deliveryMethod: 'Standard Delivery',
    paymentMethod: 'Cash on Delivery',
    trackingEvents: [
      {
        id: 't1',
        title: 'Order Placed',
        description: 'Your order has been confirmed.',
        timestamp: '2026-07-24T15:00:00Z',
        status: 'active',
      },
    ],
  },
];
