export const SEO_CONSTANTS = {
  SITE_NAME: 'Navya Collection',
  DEFAULT_TITLE: 'Navya Collection | Buy Local Boutique Fashion & Ethnic Wear Online India',
  TITLE_TEMPLATE: '%s | Navya Collection',
  DEFAULT_DESCRIPTION:
    'Shop authentic women ethnic wear, designer sarees, boutique kurtis, and men casual fashion from top verified local boutiques across India with fast nationwide delivery.',
  SITE_URL: process.env.NEXT_PUBLIC_APP_URL || 'https://navyacollection.store',
  DEFAULT_OG_IMAGE: 'https://navyacollection.store/og-image.jpg',
  TWITTER_HANDLE: undefined,
  THEME_COLOR: '#09172E',
  DEFAULT_LOCALE: 'en_IN',
  ORGANIZATION: {
    NAME: 'Navya Collection',
    LEGAL_NAME: 'Navya Collection Private Limited',
    URL: 'https://navyacollection.store',
    LOGO: 'https://navyacollection.store/images/navya-logo.png',
    FOUNDING_DATE: '2022',
    TELEPHONE: '+91-9053883125',
    EMAIL: 'helpdesk@navyacollection.store',
    ADDRESS: {
      ADDRESS_LOCALITY: 'Fatehabad',
      ADDRESS_REGION: 'Haryana',
      POSTAL_CODE: '125050',
      ADDRESS_COUNTRY: 'IN',
    },
    SAME_AS: [],
  },
  DEFAULT_KEYWORDS: [
    'Navya Collection',
    'buy clothes from local shops India',
    'local boutiques online',
    'Indian ethnic wear shopping',
    'designer sarees online',
    'boutique kurtis India',
    'men ethnic wear online',
    'kids festive fashion',
    'fashion marketplace India',
    'verified Indian boutiques',
  ],
};
