export const SEO_CONSTANTS = {
  SITE_NAME: 'Navya Collection',
  DEFAULT_TITLE: 'Navya Collection | Fashion Marketplace',
  TITLE_TEMPLATE: '%s | Navya Collection',
  DEFAULT_DESCRIPTION:
    'Navya Collection is a fashion marketplace connecting customers with local clothing stores, boutiques and fashion sellers across India.',
  SITE_URL: process.env.NEXT_PUBLIC_APP_URL || 'https://navyacollection.store',
  DEFAULT_OG_IMAGE: 'https://navyacollection.store/og-image.jpg',
  TWITTER_HANDLE: undefined,
  THEME_COLOR: '#0A2342',
  DEFAULT_LOCALE: 'en_IN',
  ORGANIZATION: {
    NAME: 'Navya Collection',
    LEGAL_NAME: 'Navya Collection Private Limited',
    URL: 'https://navyacollection.store',
    LOGO: 'https://navyacollection.store/logo.png',
    FOUNDING_DATE: '2022',
    TELEPHONE: '+91-9053883125',
    EMAIL: 'helpdesk@navyacollection.store',
    ADDRESS: {
      ADDRESS_LOCALITY: 'Fatehabad',
      ADDRESS_REGION: 'Haryana',
      POSTAL_CODE: '125050',
      ADDRESS_COUNTRY: 'IN',
    },
    SAME_AS: [],
  },
  DEFAULT_KEYWORDS: [
    'Navya Collection',
    'fashion marketplace India',
    'boutique clothing online',
    'local clothing stores',
    'Indian ethnic wear',
    'designer sarees',
    'menswear India',
    'kids festive fashion',
    'online fashion marketplace',
  ],
};

