export interface SubCategoryItem {
  id: string;
  name: string;
  slug: string;
  image: string;
  queryParam: string;
  badge?: string;
}

export interface SubCategorySection {
  id: string;
  title: string;
  items: SubCategoryItem[];
}

export interface SpotlightItem {
  id: string;
  title: string;
  subtitle?: string;
  image: string;
  slug: string;
  badge?: string;
  gradient?: string;
}

export interface MainCategoryGroup {
  id: string;
  name: string;
  slug: string;
  iconImage: string;
  badge?: string;
  banner?: {
    title: string;
    subtitle: string;
    image: string;
    link: string;
  };
  spotlights?: SpotlightItem[];
  subSections: SubCategorySection[];
}

export const MAIN_CATEGORY_GROUPS: MainCategoryGroup[] = [
  // 1. IN THE SPOTLIGHT
  {
    id: 'group_spotlight',
    name: 'In The Spotlight',
    slug: 'spotlight',
    iconImage: '/images/categories/category-spotlight.jpg',
    badge: 'TRENDING',
    banner: {
      title: 'In The Spotlight Collections',
      subtitle: 'Handpicked seasonal drops, festive highlights, top-rated trends & budget finds',
      image: '/images/categories/category-spotlight.jpg',
      link: '/shop?tag=spotlight',
    },
    spotlights: [
      {
        id: 'spot_festivals_india',
        title: 'Festivals of India',
        subtitle: 'Grand Celebrations',
        image: '/images/categories/spot-festivals-india.jpg',
        slug: '/shop?occasion=festive',
        badge: 'HOT',
        gradient: 'from-pink-600 via-purple-700 to-indigo-900',
      },
      {
        id: 'spot_new_season',
        title: 'New Season',
        subtitle: 'Fresh Arrivals',
        image: '/images/categories/spot-new-season.jpg',
        slug: '/shop?collection=new-season',
        badge: 'NEW',
        gradient: 'from-amber-700 via-rose-700 to-red-800',
      },
      {
        id: 'spot_best_sellers',
        title: 'Best Sellers',
        subtitle: 'Customer Favorites',
        image: '/images/categories/spot-best-sellers.jpg',
        slug: '/shop?filter=best_seller',
        badge: 'TOP',
        gradient: 'from-amber-600 via-yellow-700 to-amber-900',
      },
      {
        id: 'spot_korean_store',
        title: 'Korean Store',
        subtitle: 'K-Aesthetic Drops',
        image: '/images/categories/spot-korean-store.jpg',
        slug: '/shop?style=korean',
        badge: 'TREND',
        gradient: 'from-slate-700 via-zinc-800 to-neutral-900',
      },
      {
        id: 'spot_trendy_street',
        title: 'Trendy Street',
        subtitle: 'Urban & Oversized',
        image: '/images/categories/spot-trendy-street.jpg',
        slug: '/shop?style=streetwear',
        badge: 'STREET',
        gradient: 'from-orange-600 via-amber-700 to-yellow-800',
      },
      {
        id: 'spot_budget_finds',
        title: 'Budget Finds',
        subtitle: 'Under ₹999 Store',
        image: '/images/categories/spot-budget-finds.jpg',
        slug: '/shop?maxPrice=999',
        badge: 'VALUE',
        gradient: 'from-emerald-700 via-green-800 to-teal-900',
      },
    ],
    subSections: [
      {
        id: 'sec_spotlight_themes',
        title: 'Curated Themes & Trends',
        items: [
          {
            id: 'item_festivals_india',
            name: 'Festivals of India',
            slug: 'festivals-of-india',
            image: '/images/categories/spot-festivals-india.jpg',
            queryParam: 'occasion=festive',
            badge: 'FESTIVE',
          },
          {
            id: 'item_new_season',
            name: 'New Season Drops',
            slug: 'new-season',
            image: '/images/categories/spot-new-season.jpg',
            queryParam: 'collection=new-season',
            badge: 'NEW',
          },
          {
            id: 'item_korean_store',
            name: 'Korean Aesthetic',
            slug: 'korean-store',
            image: '/images/categories/spot-korean-store.jpg',
            queryParam: 'style=korean',
          },
          {
            id: 'item_genz_fashion',
            name: 'Gen Z Trends',
            slug: 'gen-z-fashion',
            image: '/images/categories/spot-genz-fashion.jpg',
            queryParam: 'style=gen-z',
          },
          {
            id: 'item_trendy_street',
            name: 'Streetwear & Oversized',
            slug: 'trendy-street',
            image: '/images/categories/spot-trendy-street.jpg',
            queryParam: 'style=streetwear',
          },
          {
            id: 'item_sports_store',
            name: 'Active & Gym Wear',
            slug: 'sports-store',
            image: '/images/categories/spot-sports-store.jpg',
            queryParam: 'category=activewear',
          },
        ],
      },
      {
        id: 'sec_spotlight_highlights',
        title: 'Popular Collections & Deals',
        items: [
          {
            id: 'item_best_sellers',
            name: 'Best Sellers',
            slug: 'best-sellers',
            image: '/images/categories/spot-best-sellers.jpg',
            queryParam: 'filter=best_seller',
            badge: 'TOP',
          },
          {
            id: 'item_top_rated',
            name: 'Top-Rated Styles',
            slug: 'top-rated',
            image: '/images/categories/spot-top-rated.jpg',
            queryParam: 'sort=rating',
            badge: '★ 4.8',
          },
          {
            id: 'item_new_on_navya',
            name: 'Fresh Arrivals',
            slug: 'new-arrivals',
            image: '/images/categories/spot-fresh-arrivals.jpg',
            queryParam: 'sort=newest',
            badge: 'NEW',
          },
          {
            id: 'item_budget_finds',
            name: 'Budget Store (Under ₹999)',
            slug: 'budget-finds',
            image: '/images/categories/spot-budget-finds.jpg',
            queryParam: 'maxPrice=999',
            badge: 'VALUE',
          },
        ],
      },
    ],
  },

  // 2. MEN
  {
    id: 'group_men',
    name: 'Men',
    slug: 'men',
    iconImage: '/images/categories/category-men.jpg',
    badge: 'POPULAR',
    banner: {
      title: "Men's Collection",
      subtitle: 'From Handcrafted Silk Kurtas & Suits to Everyday Tops, Denim & Essentials',
      image: '/images/categories/category-men.jpg',
      link: '/shop?gender=men',
    },
    spotlights: [
      {
        id: 'spot_men_kurtas',
        title: 'Kurtas & Sets',
        subtitle: 'Ethnic Celebrations',
        image: '/images/categories/men-kurtas.jpg',
        slug: '/shop?gender=men&category=men-kurtas',
        badge: 'ETHNIC',
        gradient: 'from-amber-700 via-orange-800 to-red-900',
      },
      {
        id: 'spot_men_shirts',
        title: 'Casual & Formal Shirts',
        subtitle: 'Sharp & Classic Fits',
        image: '/images/categories/men-shirts.jpg',
        slug: '/shop?gender=men&category=men-shirts',
        badge: 'POPULAR',
        gradient: 'from-blue-700 via-indigo-800 to-sky-900',
      },
      {
        id: 'spot_men_jeans',
        title: 'Jeans & Trousers',
        subtitle: 'Everyday Bottoms',
        image: '/images/categories/men-jeans.jpg',
        slug: '/shop?gender=men&category=men-jeans',
        badge: 'DENIM',
        gradient: 'from-blue-800 via-slate-800 to-slate-950',
      },
      {
        id: 'spot_men_blazers',
        title: 'Suits & Blazers',
        subtitle: 'Tailored Formals',
        image: '/images/categories/men-blazers.jpg',
        slug: '/shop?gender=men&category=men-blazers',
        badge: 'FORMAL',
        gradient: 'from-slate-800 via-blue-900 to-slate-950',
      },
      {
        id: 'spot_men_watches',
        title: 'Watches & Accessories',
        subtitle: 'Premium Accents',
        image: '/images/categories/men-accessories.jpg',
        slug: '/shop?gender=men&category=men-watches',
        badge: 'LUXURY',
        gradient: 'from-amber-600 via-yellow-700 to-stone-900',
      },
    ],
    subSections: [
      {
        id: 'sec_men_topwear',
        title: 'Topwear',
        items: [
          {
            id: 'men_shirts',
            name: 'Shirts',
            slug: 'men-shirts',
            image: '/images/categories/men-shirts.jpg',
            queryParam: 'category=men-shirts',
            badge: 'BESTSELLER',
          },
          {
            id: 'men_tshirts',
            name: 'T-Shirts',
            slug: 'men-t-shirts',
            image: '/images/categories/men-tshirts.jpg',
            queryParam: 'category=men-t-shirts',
          },
          {
            id: 'men_polos',
            name: 'Polos',
            slug: 'men-polos',
            image: '/images/categories/men-polos.jpg',
            queryParam: 'category=men-polos',
          },
          {
            id: 'men_sweatshirts',
            name: 'Sweatshirts & Hoodies',
            slug: 'men-sweatshirts',
            image: '/images/categories/men-sweatshirts.jpg',
            queryParam: 'category=men-sweatshirts',
          },
          {
            id: 'men_sweaters',
            name: 'Sweaters',
            slug: 'men-sweaters',
            image: '/images/categories/men-sweaters.jpg',
            queryParam: 'category=men-sweaters',
          },
        ],
      },
      {
        id: 'sec_men_bottomwear',
        title: 'Bottomwear',
        items: [
          {
            id: 'men_jeans',
            name: 'Jeans / Denims',
            slug: 'men-jeans',
            image: '/images/categories/men-jeans.jpg',
            queryParam: 'category=men-jeans',
            badge: 'DENIM',
          },
          {
            id: 'men_trousers',
            name: 'Trousers & Chinos',
            slug: 'men-trousers',
            image: '/images/categories/men-trousers.jpg',
            queryParam: 'category=men-trousers',
          },
          {
            id: 'men_cargos',
            name: 'Cargo Pants',
            slug: 'men-cargo-pants',
            image: '/images/categories/men-cargos.jpg',
            queryParam: 'category=men-cargo-pants',
            badge: 'TREND',
          },
          {
            id: 'men_shorts',
            name: 'Shorts',
            slug: 'men-shorts',
            image: '/images/categories/men-shorts.jpg',
            queryParam: 'category=men-shorts',
          },
          {
            id: 'men_trackpants',
            name: 'Track Pants',
            slug: 'men-track-pants',
            image: '/images/categories/men-trackpants.jpg',
            queryParam: 'category=men-track-pants',
          },
        ],
      },
      {
        id: 'sec_men_ethnic',
        title: 'Ethnic & Festive Wear',
        items: [
          {
            id: 'men_kurtas',
            name: 'Kurtas',
            slug: 'men-kurtas',
            image: '/images/categories/men-kurtas.jpg',
            queryParam: 'category=men-kurtas',
            badge: 'ETHNIC',
          },
          {
            id: 'men_kurta_sets',
            name: 'Kurta Sets',
            slug: 'men-kurta-sets',
            image: '/images/categories/men-kurta-sets.jpg',
            queryParam: 'category=men-kurta-sets',
          },
          {
            id: 'men_ethnic_shirts',
            name: 'Ethnic Shirts',
            slug: 'men-ethnic-shirts',
            image: '/images/categories/men-ethnic-shirts.jpg',
            queryParam: 'category=men-ethnic-shirts',
          },
          {
            id: 'men_sherwanis',
            name: 'Sherwanis',
            slug: 'men-sherwanis',
            image: '/images/categories/men-sherwanis.jpg',
            queryParam: 'category=men-sherwanis',
            badge: 'WEDDING',
          },
          {
            id: 'men_nehru_jackets',
            name: 'Nehru Jackets',
            slug: 'men-nehru-jackets',
            image: '/images/categories/men-blazers-alt.jpg',
            queryParam: 'category=men-nehru-jackets',
          },
        ],
      },
      {
        id: 'sec_men_formal',
        title: 'Formal & Party Wear',
        items: [
          {
            id: 'men_formal_shirts',
            name: 'Formal Shirts',
            slug: 'men-formal-shirts',
            image: '/images/categories/men-formal-shirts.jpg',
            queryParam: 'category=men-formal-shirts',
          },
          {
            id: 'men_formal_trousers',
            name: 'Formal Trousers',
            slug: 'men-formal-trousers',
            image: '/images/categories/men-formal-trousers.jpg',
            queryParam: 'category=men-formal-trousers',
          },
          {
            id: 'men_blazers',
            name: 'Blazers',
            slug: 'men-blazers',
            image: '/images/categories/men-blazers.jpg',
            queryParam: 'category=men-blazers',
            badge: 'PREMIUM',
          },
          {
            id: 'men_suits',
            name: 'Suits & Waistcoats',
            slug: 'men-suits',
            image: '/images/categories/men-suits.jpg',
            queryParam: 'category=men-suits',
          },
        ],
      },
      {
        id: 'sec_men_outerwear',
        title: 'Outerwear & Activewear',
        items: [
          {
            id: 'men_outer_jackets',
            name: 'Jackets & Coats',
            slug: 'men-jackets',
            image: '/images/categories/men-outer-jackets.jpg',
            queryParam: 'category=men-jackets',
          },
          {
            id: 'men_windcheaters',
            name: 'Windcheaters & Raincoats',
            slug: 'men-windcheaters',
            image: '/images/categories/men-windcheaters.jpg',
            queryParam: 'category=men-windcheaters',
            badge: 'OUTDOOR',
          },
          {
            id: 'men_sports_tshirts',
            name: 'Sports T-Shirts',
            slug: 'men-sports-t-shirts',
            image: '/images/categories/men-sports-tshirts.jpg',
            queryParam: 'category=men-sports-t-shirts',
          },
          {
            id: 'men_tracksuits',
            name: 'Tracksuits & Active Sets',
            slug: 'men-tracksuits',
            image: '/images/categories/men-sports-gear.jpg',
            queryParam: 'category=men-tracksuits',
            badge: 'ACTIVE',
          },
        ],
      },
      {
        id: 'sec_men_accessories',
        title: "Men's Accessories",
        items: [
          {
            id: 'men_wallets',
            name: 'Wallets',
            slug: 'men-wallets',
            image: '/images/categories/men-wallets.jpg',
            queryParam: 'category=men-wallets',
          },
          {
            id: 'men_belts',
            name: 'Belts',
            slug: 'men-belts',
            image: '/images/categories/men-belts.jpg',
            queryParam: 'category=men-belts',
          },
          {
            id: 'men_watches',
            name: 'Watches',
            slug: 'men-watches',
            image: '/images/categories/men-accessories.jpg',
            queryParam: 'category=men-watches',
            badge: 'LUXURY',
          },
          {
            id: 'men_sunglasses',
            name: 'Sunglasses',
            slug: 'men-sunglasses',
            image: '/images/categories/men-sunglasses.jpg',
            queryParam: 'category=men-sunglasses',
          },
          {
            id: 'men_caps_hats',
            name: 'Caps & Hats',
            slug: 'men-caps-hats',
            image: '/images/categories/men-all-accessories.jpg',
            queryParam: 'category=men-caps-hats',
          },
          {
            id: 'men_bags',
            name: 'Bags & Backpacks',
            slug: 'men-bags-backpacks',
            image: '/images/categories/men-all-accessories.jpg',
            queryParam: 'category=men-bags-backpacks',
          },
          {
            id: 'men_ties',
            name: 'Ties & Pocket Squares',
            slug: 'men-ties',
            image: '/images/categories/men-ties.jpg',
            queryParam: 'category=men-ties',
          },
        ],
      },
      {
        id: 'sec_men_essentials',
        title: "Men's Essentials & Innerwear",
        items: [
          {
            id: 'men_briefs',
            name: 'Briefs & Boxers',
            slug: 'men-briefs',
            image: '/images/categories/men-briefs.jpg',
            queryParam: 'category=men-briefs',
          },
          {
            id: 'men_vests',
            name: 'Vests & Undershirts',
            slug: 'men-vests',
            image: '/images/categories/men-vests.jpg',
            queryParam: 'category=men-vests',
          },
          {
            id: 'men_socks',
            name: 'Socks',
            slug: 'men-socks',
            image: '/images/categories/men-ankle-socks.jpg',
            queryParam: 'category=men-ankle-socks',
          },
          {
            id: 'men_thermals',
            name: 'Thermals',
            slug: 'men-thermals',
            image: '/images/categories/men-thermals.jpg',
            queryParam: 'category=men-thermals',
            badge: 'WARM',
          },
          {
            id: 'men_lounge_pants',
            name: 'Loungewear & Sleepwear',
            slug: 'men-lounge-pants',
            image: '/images/categories/men-trackpants-alt.jpg',
            queryParam: 'category=men-lounge-pants',
            badge: 'COMFORT',
          },
        ],
      },
    ],
  },

  // 3. WOMEN
  {
    id: 'group_women',
    name: 'Women',
    slug: 'women',
    iconImage: '/images/categories/category-women.jpg',
    badge: 'HOT',
    banner: {
      title: "Women's Collection",
      subtitle: 'Pure Heritage Sarees, Bridal Lehengas, Kurtis, Western Tops, Bags & Essentials',
      image: '/images/categories/category-women.jpg',
      link: '/shop?gender=women',
    },
    spotlights: [
      {
        id: 'spot_women_sarees',
        title: 'Sarees & Silk',
        subtitle: 'Banarasi & Kanjeevaram',
        image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=300',
        slug: '/shop?gender=women&category=women-sarees',
        badge: 'HERITAGE',
        gradient: 'from-rose-700 via-pink-800 to-purple-950',
      },
      {
        id: 'spot_women_lehengas',
        title: 'Bridal Lehengas',
        subtitle: 'Royal Wedding Sets',
        image: 'https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=300',
        slug: '/shop?gender=women&category=women-lehengas',
        badge: 'BRIDAL',
        gradient: 'from-amber-600 via-rose-700 to-red-900',
      },
      {
        id: 'spot_women_kurta_sets',
        title: 'Kurta Sets & Suits',
        subtitle: 'Festive & Daily Wear',
        image: 'https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=300',
        slug: '/shop?gender=women&category=women-kurta-sets',
        badge: 'FESTIVE',
        gradient: 'from-teal-700 via-emerald-800 to-cyan-950',
      },
      {
        id: 'spot_women_dresses',
        title: 'Western & Dresses',
        subtitle: 'Maxis, Gowns & Tops',
        image: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=300',
        slug: '/shop?gender=women&category=women-dresses',
        badge: 'TREND',
        gradient: 'from-indigo-700 via-purple-800 to-navy',
      },
      {
        id: 'spot_women_handbags',
        title: 'Handbags & Clutches',
        subtitle: 'Designer Bags & Accessories',
        image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=300',
        slug: '/shop?gender=women&category=women-handbags',
        badge: 'LUXURY',
        gradient: 'from-fuchsia-700 via-pink-700 to-rose-900',
      },
    ],
    subSections: [
      {
        id: 'sec_women_indian',
        title: 'Indian & Festive Wear',
        items: [
          {
            id: 'women_sarees',
            name: 'Sarees',
            slug: 'women-sarees',
            image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=300',
            queryParam: 'category=women-sarees',
            badge: 'HERITAGE',
          },
          {
            id: 'women_lehengas',
            name: 'Lehenga Choli',
            slug: 'women-lehengas',
            image: 'https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=300',
            queryParam: 'category=women-lehengas',
            badge: 'BRIDAL',
          },
          {
            id: 'women_kurta_sets',
            name: 'Kurta Sets & Salwar Suits',
            slug: 'women-kurta-sets',
            image: 'https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=300',
            queryParam: 'category=women-kurta-sets',
            badge: 'POPULAR',
          },
          {
            id: 'women_kurtas',
            name: 'Kurtas & Kurtis',
            slug: 'women-kurtas',
            image: 'https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=300',
            queryParam: 'category=women-kurtas',
          },
          {
            id: 'women_ethnic_dresses',
            name: 'Ethnic Gowns & Dresses',
            slug: 'women-ethnic-dresses',
            image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=300',
            queryParam: 'category=women-ethnic-dresses',
          },
        ],
      },
      {
        id: 'sec_women_western',
        title: 'Western & Casual Wear',
        items: [
          {
            id: 'women_dresses',
            name: 'Dresses & Gowns',
            slug: 'women-dresses',
            image: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=300',
            queryParam: 'category=women-dresses',
            badge: 'TRENDING',
          },
          {
            id: 'women_tops_tees',
            name: 'Tops & Tees',
            slug: 'women-tops-tees',
            image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=300',
            queryParam: 'category=women-tops-tees',
          },
          {
            id: 'women_shirts',
            name: 'Shirts',
            slug: 'women-shirts',
            image: 'https://images.unsplash.com/photo-1598554747436-c9293d6a588f?w=300',
            queryParam: 'category=women-shirts',
          },
          {
            id: 'women_coord_sets',
            name: 'Co-ord Sets & Jumpsuits',
            slug: 'women-coord-sets',
            image: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=300',
            queryParam: 'category=women-coord-sets',
            badge: 'HOT',
          },
          {
            id: 'women_skirts',
            name: 'Skirts',
            slug: 'women-skirts',
            image: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=300',
            queryParam: 'category=women-skirts',
          },
          {
            id: 'women_jeans',
            name: 'Jeans & Trousers',
            slug: 'women-jeans',
            image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=300',
            queryParam: 'category=women-jeans',
          },
          {
            id: 'women_shorts',
            name: 'Shorts',
            slug: 'women-shorts',
            image: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=300',
            queryParam: 'category=women-shorts',
          },
        ],
      },
      {
        id: 'sec_women_winter_outerwear',
        title: 'Winterwear & Outerwear',
        items: [
          {
            id: 'women_jackets',
            name: 'Jackets & Shrugs',
            slug: 'women-jackets',
            image: 'https://images.unsplash.com/photo-1544441893-675973e31985?w=300',
            queryParam: 'category=women-jackets',
          },
          {
            id: 'women_sweaters',
            name: 'Sweaters & Cardigans',
            slug: 'women-sweaters',
            image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=300',
            queryParam: 'category=women-sweaters',
          },
          {
            id: 'women_sweatshirts',
            name: 'Sweatshirts & Hoodies',
            slug: 'women-sweatshirts',
            image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=300',
            queryParam: 'category=women-sweatshirts',
          },
          {
            id: 'women_coats',
            name: 'Long Coats',
            slug: 'women-coats',
            image: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=300',
            queryParam: 'category=women-coats',
            badge: 'WINTER',
          },
        ],
      },
      {
        id: 'sec_women_active_sleep',
        title: 'Activewear & Sleepwear',
        items: [
          {
            id: 'women_active_all',
            name: 'Activewear Sets & Tights',
            slug: 'women-activewear-sets',
            image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=300',
            queryParam: 'category=women-activewear-sets',
          },
          {
            id: 'women_sports_tops',
            name: 'Sports Tops & Bras',
            slug: 'women-sports-tops',
            image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=300',
            queryParam: 'category=women-sports-tops',
          },
          {
            id: 'women_night_suits',
            name: 'Night Suits',
            slug: 'women-night-suits',
            image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=300',
            queryParam: 'category=women-night-suits',
            badge: 'COZY',
          },
          {
            id: 'women_night_dresses',
            name: 'Night Dresses & Loungewear',
            slug: 'women-night-dresses',
            image: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=300',
            queryParam: 'category=women-night-dresses',
          },
        ],
      },
      {
        id: 'sec_women_bags',
        title: 'Handbags & Clutches',
        items: [
          {
            id: 'women_handbags',
            name: 'Handbags',
            slug: 'women-handbags',
            image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=300',
            queryParam: 'category=women-handbags',
            badge: 'LUXURY',
          },
          {
            id: 'women_sling_bags',
            name: 'Sling Bags',
            slug: 'women-sling-bags',
            image: 'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=300',
            queryParam: 'category=women-sling-bags',
          },
          {
            id: 'women_shoulder_bags',
            name: 'Shoulder & Tote Bags',
            slug: 'women-shoulder-bags',
            image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=300',
            queryParam: 'category=women-shoulder-bags',
          },
          {
            id: 'women_backpacks',
            name: 'Backpacks',
            slug: 'women-backpacks',
            image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=300',
            queryParam: 'category=women-backpacks',
          },
          {
            id: 'women_clutches',
            name: 'Clutches & Potlis',
            slug: 'women-clutches',
            image: 'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=300',
            queryParam: 'category=women-clutches',
          },
        ],
      },
      {
        id: 'sec_women_accessories_other',
        title: 'Jewellery & Fashion Accessories',
        items: [
          {
            id: 'women_jewellery',
            name: 'Jewellery & Sets',
            slug: 'women-jewellery',
            image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=300',
            queryParam: 'category=women-jewellery',
            badge: 'SPARKLE',
          },
          {
            id: 'women_watches',
            name: 'Watches',
            slug: 'women-watches',
            image: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=300',
            queryParam: 'category=women-watches',
            badge: 'PREMIUM',
          },
          {
            id: 'women_sunglasses',
            name: 'Sunglasses',
            slug: 'women-sunglasses',
            image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=300',
            queryParam: 'category=women-sunglasses',
          },
          {
            id: 'women_belts',
            name: 'Belts',
            slug: 'women-belts',
            image: 'https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=300',
            queryParam: 'category=women-belts',
          },
          {
            id: 'women_scarves',
            name: 'Scarves, Stoles & Dupattas',
            slug: 'women-scarves-stoles',
            image: 'https://images.unsplash.com/photo-1607344645866-009c320b5ab8?w=300',
            queryParam: 'category=women-scarves-stoles',
          },
          {
            id: 'women_hair_acc',
            name: 'Hair Accessories',
            slug: 'women-hair-accessories',
            image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=300',
            queryParam: 'category=women-hair-accessories',
          },
        ],
      },
      {
        id: 'sec_women_innerwear',
        title: 'Essentials & Lingerie',
        items: [
          {
            id: 'women_bras',
            name: 'Bras',
            slug: 'women-bras',
            image: 'https://images.unsplash.com/photo-1596704017254-9b121068fb31?w=300',
            queryParam: 'category=women-bras',
          },
          {
            id: 'women_panties',
            name: 'Panties',
            slug: 'women-panties',
            image: 'https://images.unsplash.com/photo-1596704017254-9b121068fb31?w=300',
            queryParam: 'category=women-panties',
          },
          {
            id: 'women_lingerie',
            name: 'Lingerie Sets',
            slug: 'women-lingerie',
            image: 'https://images.unsplash.com/photo-1596704017254-9b121068fb31?w=300',
            queryParam: 'category=women-lingerie',
            badge: 'HOT',
          },
          {
            id: 'women_camisoles',
            name: 'Camisoles & Slips',
            slug: 'women-camisoles',
            image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300',
            queryParam: 'category=women-camisoles',
          },
          {
            id: 'women_shapewear',
            name: 'Shapewear',
            slug: 'women-shapewear-bodysuits',
            image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300',
            queryParam: 'category=women-shapewear-bodysuits',
            badge: 'CONTOUR',
          },
          {
            id: 'women_thermals',
            name: 'Thermals & Winter Base',
            slug: 'women-thermals',
            image: 'https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=300',
            queryParam: 'category=women-thermals',
            badge: 'WARM',
          },
        ],
      },
    ],
  },

  // 4. KIDS
  {
    id: 'group_kids',
    name: 'Kids',
    slug: 'kids',
    iconImage: '/images/categories/category-kids.jpg',
    badge: 'CUTE',
    banner: {
      title: "Kids' Fashion World",
      subtitle: 'Soft Newborn Sets, Boys & Girls Ethnic Outfits, Casuals, Teens & Essentials',
      image: '/images/categories/category-kids.jpg',
      link: '/shop?gender=kids',
    },
    spotlights: [
      {
        id: 'spot_kids_ethnic',
        title: 'Kids Ethnic Wear',
        subtitle: 'Kurtas, Sherwanis & Lehengas',
        image: 'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?w=300',
        slug: '/shop?gender=kids&category=boys-ethnic-wear',
        badge: 'FESTIVE',
        gradient: 'from-amber-600 via-orange-700 to-rose-900',
      },
      {
        id: 'spot_kids_baby',
        title: 'Baby & Newborn',
        subtitle: 'Soft Cotton & Rompers',
        image: 'https://images.unsplash.com/photo-1522771930-78848d9293e8?w=300',
        slug: '/shop?gender=kids&category=baby-fashion',
        badge: 'SOFT',
        gradient: 'from-pink-600 via-rose-700 to-purple-900',
      },
      {
        id: 'spot_kids_girls',
        title: 'Girls Frocks & Gowns',
        subtitle: 'Party Dresses & Sets',
        image: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=300',
        slug: '/shop?gender=kids&category=girls-fashion',
        badge: 'CUTE',
        gradient: 'from-purple-600 via-fuchsia-700 to-pink-900',
      },
      {
        id: 'spot_kids_boys',
        title: 'Boys Tops & Denims',
        subtitle: 'Tees, Shirts & Jeans',
        image: 'https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?w=300',
        slug: '/shop?gender=kids&category=boys-fashion',
        badge: 'COOL',
        gradient: 'from-blue-600 via-indigo-700 to-sky-900',
      },
      {
        id: 'spot_kids_teens',
        title: 'Teen Trends',
        subtitle: 'Youth Aesthetics',
        image: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=300',
        slug: '/shop?gender=kids&category=teen-trends',
        badge: 'TREND',
        gradient: 'from-teal-600 via-emerald-700 to-cyan-900',
      },
    ],
    subSections: [
      {
        id: 'sec_kids_baby',
        title: 'Baby (0-2 Yrs)',
        items: [
          {
            id: 'baby_newborn',
            name: 'Newborn Essentials',
            slug: 'baby-newborn',
            image: 'https://images.unsplash.com/photo-1522771930-78848d9293e8?w=300',
            queryParam: 'category=baby-newborn',
            badge: 'SOFT',
          },
          {
            id: 'baby_boys',
            name: 'Baby Boys Outfits',
            slug: 'baby-boys',
            image: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=300',
            queryParam: 'category=baby-boys',
          },
          {
            id: 'baby_girls',
            name: 'Baby Girls Outfits',
            slug: 'baby-girls',
            image: 'https://images.unsplash.com/photo-1522771930-78848d9293e8?w=300',
            queryParam: 'category=baby-girls',
          },
          {
            id: 'baby_rompers',
            name: 'Rompers & Onesies',
            slug: 'baby-rompers',
            image: 'https://images.unsplash.com/photo-1522771930-78848d9293e8?w=300',
            queryParam: 'category=baby-rompers',
            badge: 'CUTE',
          },
        ],
      },
      {
        id: 'sec_kids_boys',
        title: 'Boys (2-14 Yrs)',
        items: [
          {
            id: 'boys_tshirts',
            name: 'T-Shirts & Polos',
            slug: 'boys-t-shirts',
            image: 'https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?w=300',
            queryParam: 'category=boys-t-shirts',
          },
          {
            id: 'boys_shirts',
            name: 'Shirts',
            slug: 'boys-shirts',
            image: 'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?w=300',
            queryParam: 'category=boys-shirts',
          },
          {
            id: 'boys_jeans',
            name: 'Jeans & Trousers',
            slug: 'boys-jeans',
            image: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=300',
            queryParam: 'category=boys-jeans',
          },
          {
            id: 'boys_shorts',
            name: 'Shorts & Track Pants',
            slug: 'boys-shorts',
            image: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=300',
            queryParam: 'category=boys-shorts',
          },
          {
            id: 'boys_ethnic',
            name: 'Ethnic Wear (Kurtas & Sherwanis)',
            slug: 'boys-ethnic-wear',
            image: 'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?w=300',
            queryParam: 'category=boys-ethnic-wear',
            badge: 'FESTIVE',
          },
          {
            id: 'boys_jackets',
            name: 'Jackets & Sweatshirts',
            slug: 'boys-jackets',
            image: 'https://images.unsplash.com/photo-1544441893-675973e31985?w=300',
            queryParam: 'category=boys-jackets',
          },
        ],
      },
      {
        id: 'sec_kids_girls',
        title: 'Girls (2-14 Yrs)',
        items: [
          {
            id: 'girls_dresses',
            name: 'Dresses & Frocks',
            slug: 'girls-dresses',
            image: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=300',
            queryParam: 'category=girls-dresses',
            badge: 'CUTE',
          },
          {
            id: 'girls_tops_tees',
            name: 'Tops & Tees',
            slug: 'girls-tops-tees',
            image: 'https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?w=300',
            queryParam: 'category=girls-tops-tees',
          },
          {
            id: 'girls_ethnic',
            name: 'Ethnic Wear (Lehengas & Suits)',
            slug: 'girls-ethnic-wear',
            image: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=300',
            queryParam: 'category=girls-ethnic-wear',
            badge: 'ROYAL',
          },
          {
            id: 'girls_skirts',
            name: 'Skirts & Jumpsuits',
            slug: 'girls-skirts',
            image: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=300',
            queryParam: 'category=girls-skirts',
          },
          {
            id: 'girls_jeans',
            name: 'Jeans & Trousers',
            slug: 'girls-jeans-trousers',
            image: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=300',
            queryParam: 'category=girls-jeans-trousers',
          },
          {
            id: 'girls_jackets',
            name: 'Jackets & Shrugs',
            slug: 'girls-jackets',
            image: 'https://images.unsplash.com/photo-1544441893-675973e31985?w=300',
            queryParam: 'category=girls-jackets',
          },
        ],
      },
      {
        id: 'sec_kids_teens',
        title: 'Teens Fashion',
        items: [
          {
            id: 'teens_boys',
            name: 'Teen Boys',
            slug: 'teen-boys',
            image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=300',
            queryParam: 'category=teen-boys',
          },
          {
            id: 'teens_girls',
            name: 'Teen Girls',
            slug: 'teen-girls',
            image: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=300',
            queryParam: 'category=teen-girls',
          },
          {
            id: 'teens_trends',
            name: 'Teen Street Trends',
            slug: 'teen-trends',
            image: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=300',
            queryParam: 'category=teen-trends',
            badge: 'VIRAL',
          },
        ],
      },
      {
        id: 'sec_kids_essentials',
        title: 'Kids Essentials',
        items: [
          {
            id: 'kids_innerwear',
            name: 'Innerwear & Vests',
            slug: 'kids-innerwear',
            image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300',
            queryParam: 'category=kids-innerwear',
          },
          {
            id: 'kids_socks',
            name: 'Socks',
            slug: 'kids-socks',
            image: 'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=300',
            queryParam: 'category=kids-socks',
          },
          {
            id: 'kids_nightwear',
            name: 'Nightwear & Loungewear',
            slug: 'kids-nightwear',
            image: 'https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?w=300',
            queryParam: 'category=kids-nightwear',
          },
          {
            id: 'kids_thermals',
            name: 'Thermals & Warmers',
            slug: 'kids-thermals',
            image: 'https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=300',
            queryParam: 'category=kids-thermals',
            badge: 'WARM',
          },
        ],
      },
    ],
  },

  // 5. NAVYA COLLECTION SHOPS
  {
    id: 'group_shops',
    name: 'Navya Collection Shops',
    slug: 'shops',
    iconImage: '/images/categories/category-shops.jpg',
    badge: 'BOUTIQUES',
    banner: {
      title: 'Navya Partner Boutiques',
      subtitle:
        'Shop directly from authentic designer boutiques, verified artisans & premium stores',
      image: '/images/categories/category-shops.jpg',
      link: '/shops',
    },
    subSections: [
      {
        id: 'sec_shops_grid',
        title: 'Explore Boutiques',
        items: [
          {
            id: 'shops_all',
            name: 'All Boutiques',
            slug: 'all-shops',
            image: '/images/categories/shops-all.jpg',
            queryParam: 'view=all-shops',
            badge: 'ALL',
          },
          {
            id: 'shops_new',
            name: 'New Stores',
            slug: 'new-shops',
            image: '/images/categories/shops-trending.jpg',
            queryParam: 'filter=new_shops',
            badge: 'NEW',
          },
          {
            id: 'shops_trending',
            name: 'Trending Boutiques',
            slug: 'trending-shops',
            image: '/images/categories/shops-trending.jpg',
            queryParam: 'filter=trending_shops',
            badge: 'POPULAR',
          },
          {
            id: 'shops_top_rated',
            name: 'Top-Rated Boutiques',
            slug: 'top-rated-shops',
            image: '/images/categories/shops-all.jpg',
            queryParam: 'filter=top_rated_shops',
            badge: '★ 4.9',
          },
        ],
      },
    ],
  },
];
